#pragma once

#include <QString>
#include <functional>
#include <memory>

#include <gst/gst.h>

namespace radio::audio {

class GstEngineThread;
class GstSourcePipeline;
class MixEngine;

// One fire-and-forget instance of a triggered cart-wall clip. Each trigger
// creates a fresh instance — deliberately NOT a reusable pool, so
// retriggering the same cart overlaps a new instance rather than
// restarting, matching real cart-machine behavior. Self-cleans once
// playback finishes (GstSourcePipeline's own EOS callback).
//
// Like DeckEngine, this composes an independent GstSourcePipeline
// registered as its own source in the shared MixEngine, rather than a bin
// dynamically attached into a live shared mixer — the same change that
// eliminated DeckEngine's GStreamer STATE_LOCK/STREAM_LOCK deadlock
// applies equally here. All methods must run on the engine thread (i.e.
// from inside a GstEngineThread::invoke lambda).
class CartSlotPlayer {
public:
    // token identifies this specific instance to the caller (see
    // CartWallEngine::trigger()) — generated by the caller, not here, since
    // trigger() needs to hand it back synchronously before this object
    // (built asynchronously on the engine thread) even exists.
    CartSlotPlayer(MixEngine* mixEngine, GstEngineThread* engineThread, QString uri, QString token,
        std::function<void(CartSlotPlayer*)> onFinished);
    ~CartSlotPlayer();

    // Builds the clip's own independent pipeline, registers it with
    // MixEngine, and starts it playing immediately.
    bool start();

    // Detaches from MixEngine and tears down the pipeline. Idempotent —
    // safe to call from the destructor even if an EOS-triggered teardown
    // already ran.
    void teardown();

    // The token trigger() returned for this instance (see CartWallEngine::
    // isActive()).
    const QString& token() const { return m_mixSourceId; }

private:
    MixEngine* m_mixEngine;
    GstEngineThread* m_engineThread;
    QString m_uri;
    std::function<void(CartSlotPlayer*)> m_onFinished;

    // Unique per-instance MixEngine source id (required since multiple
    // simultaneous instances of the SAME clip are a legitimate, deliberate
    // case — see CartWallEngine's class comment) that doubles as the
    // caller-visible completion token (see the constructor's doc comment).
    QString m_mixSourceId;

    std::unique_ptr<GstSourcePipeline> m_pipeline;
    bool m_tornDown = false;

    // Same ReplayGain-based auto-gain math as DeckEngine::recomputeTrim(),
    // minus the manual trimVolume knob a deck has (a cart has no equivalent
    // UI control) -- always applied when the clip has ReplayGain tags, since
    // a jingle is a one-shot clip meant to sit at the same target loudness
    // as the decks around it, not something a user rides gain on. No-op
    // (leaves trim at MixEngine::attachSource()'s default 1.0) for a clip
    // with no ReplayGain tags.
    void recomputeTrim();
};

} // namespace radio::audio
